In [1]:
import torch
from torch_sparse import spmm

index = torch.tensor([[0, 0, 1, 2, 2],
                      [0, 2, 1, 0, 1]])
value = torch.Tensor([1, 2, 4, 1, 3])
matrix = torch.Tensor([[1, 4], [2, 5], [3, 6]])

matrix

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [2]:
matrix.size(0), matrix.size(1)

(3, 2)

In [3]:
matrix.dim()

2

In [4]:
matrix.unsqueeze(-1)

tensor([[[1.],
         [4.]],

        [[2.],
         [5.]],

        [[3.],
         [6.]]])

In [5]:
row, col = index
row, col

(tensor([0, 0, 1, 2, 2]), tensor([0, 2, 1, 0, 1]))

In [6]:
matrix = matrix if matrix.dim() > 1 else matrix.unsqueeze(-1)
matrix

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [7]:
out = matrix[col]
out

tensor([[1., 4.],
        [3., 6.],
        [2., 5.],
        [1., 4.],
        [2., 5.]])

In [8]:
m = 3
out = torch.scatter_add(out, row, dim=0, dim_size=m)
out

TypeError: scatter_add() received an invalid combination of arguments - got (Tensor, Tensor, dim_size=int, dim=int), but expected one of:
 * (Tensor input, name dim, Tensor index, Tensor src)
      didn't match because some of the keywords were incorrect: dim_size, dim
 * (Tensor input, int dim, Tensor index, Tensor src)
      didn't match because some of the keywords were incorrect: dim_size, dim


In [ ]:
out = spmm(index, value, 3, 3, matrix)
